Sparql Unicorn Goes GIS Ontology Documentation: Model3DPage Class Reference
Model3DPage Class Reference
Public Member Functions
generatePageWidget (self, graph, templates, foundmedia, subject, f, onlybody=False)
generateCollectionWidget (self, graph, templates, subject, f)
generatePageView (self, headertemplate, footertemplate, g, f)
Public Attributes
outpath
deploypath
prefixnamespace
imagemetadata
Member Function Documentation
generateCollectionWidget()
generateCollectionWidget (self, graph, templates, subject, f)
    def generateCollectionWidget(self,graph,templates,subject,f):
        print("CollectionWidget")
generatePageView()
generatePageView (self, headertemplate, footertemplate, g, f)
    def generatePageView(self,headertemplate,footertemplate,g,f):
        f.write(str(headertemplate))
        print("PageView")
generatePageWidget()
generatePageWidget (self, graph, templates, foundmedia, subject, f, onlybody = False)
    def generatePageWidget(self,graph,templates,foundmedia,subject,f,onlybody=False):
        print("PageWidget")
        if len(foundmedia["mesh"]) > 0 and len(image3dannos) > 0:
            if self.iiif:
                iiifmanifestpaths["default"].append(
                    IIIFAPIExporter.generateIIIFManifest(graph, self.outpath, self.deploypath, foundmedia["mesh"],
                                                         image3dannos, annobodies, str(subject), self.prefixnamespace,
                                                         imagetoURI, self.imagemetadata, DocConfig.metadatanamespaces,
                                                         foundlabel, comment, thetypes, predobjmap, "Model"))
            for anno in image3dannos:
                if ("POINT" in anno["value"].upper() or "POLYGON" in anno["value"].upper() or "LINESTRING" in anno[
                    "value"].upper()):
                    f.write(templates["threejstemplate"].replace("{{wktstring}}", anno["value"]).replace("{{meshurls}}",
                                                                                                         str(list(
                                                                                                             foundmedia[
                                                                                                                 "mesh"]))))
        elif len(foundmedia["mesh"]) > 0 and len(image3dannos) == 0:
            print("Found 3D Model: " + str(foundmedia["mesh"]))
            if self.iiif:
                iiifmanifestpaths["default"].append(
                    IIIFAPIExporter.generateIIIFManifest(graph, self.outpath, self.deploypath, foundmedia["mesh"],
                                                         image3dannos, annobodies, str(subject), self.prefixnamespace,
                                                         imagetoURI, self.imagemetadata, DocConfig.metadatanamespaces,
                                                         foundlabel, comment, thetypes, predobjmap, "Model"))
            for curitem in foundmedia["mesh"]:
                format = "ply"
                if ".nxs" in curitem or ".nxz" in curitem:
                    format = "nexus"
                elif format == "gltf":
                    f.write(templates["threejstemplate"].replace("{{wktstring}}", "").replace("{{meshurls}}", "[]"))
                f.write(templates["3dtemplate"].replace("{{meshurl}}", curitem).replace("{{meshformat}}", format))
                break
        elif len(foundmedia["mesh"]) == 0 and len(image3dannos) > 0:
            for anno in image3dannos:
                if ("POINT" in anno["value"].upper() or "POLYGON" in anno["value"].upper() or "LINESTRING" in anno[
                    "value"].upper()):
                    f.write(templates["threejstemplate"].replace("{{wktstring}}", anno["value"]).replace("{{meshurls}}",
                                                                                                         "[]"))
References OntDocGeneration.iiif.
Referenced by BibPage.generateCollectionWidget(), LexiconPage.generateCollectionWidget(), ObservationPage.generateCollectionWidget(), and PersonPage.generateCollectionWidget().
Member Data Documentation
deploypath
deploypath
Referenced by OntDocGeneration.createHTML(), OntDocGeneration.generateOntDocForNameSpace(), and OntDocGeneration.replaceStandardVariables().
imagemetadata
imagemetadata
Referenced by OntDocGeneration.createHTML().
outpath
outpath
Referenced by OntDocGeneration.createHTML(), and OntDocGeneration.generateOntDocForNameSpace().
prefixnamespace
prefixnamespace
Referenced by OntDocGeneration.createHTML().