SPARQLing Unicorn Ontology Documentation: GraphViewerPage Class Reference
GraphViewerPage Class Reference
Public Member Functions
def pageWidgetConstraint (self)
def collectionConstraint (self)
def generatePageWidget (self, graph, subject, f, onlybody=False)
def generateCollectionWidget (self, graph, templates, subject, f)
def generatePageView (self, headertemplate, footertemplate, g, f)
Member Function Documentation
collectionConstraint()
def collectionConstraint (self)
     def collectionConstraint(self):
         return DocConfig.collectionclasses
generateCollectionWidget()
def generateCollectionWidget (self, graph, templates, subject, f)
     def generateCollectionWidget(self,graph,templates,subject,f):
         print("CollectionWidget")
generatePageView()
def generatePageView (self, headertemplate, footertemplate, g, f)
     def generatePageView(self,headertemplate,footertemplate,g,f):
         f.write(str(headertemplate))
         print("PageView")
generatePageWidget()
def generatePageWidget (self, graph, subject, f, onlybody = False)
     def generatePageWidget(self,graph,subject,f,onlybody=False):
         print("PageWidget")
Referenced by BibPage.generateCollectionWidget(), LexiconPage.generateCollectionWidget(), ObservationPage.generateCollectionWidget(), and PersonPage.generateCollectionWidget().
pageWidgetConstraint()
def pageWidgetConstraint (self)
     def pageWidgetConstraint(self):
         print("PageWidgetConstraint")
         return []