name: SPARQLing Unicorn Ontology Documentation

permissions:
  contents: write

on:
  workflow_call:
    inputs:
      rdffilepath:
        required: true
        type: string
      docpath:
        required: true
        default: docs 
        type: string
      prefixns:
        required: true
        default: http://www.sparqlunicorn.link/data/
        type: string
      prefixnsshort:
        required: true
        default: suni
        type: string
      indexpages:
        required: false
        default: true
        type: boolean
      ghpages:
        required: false
        default: true
        type: boolean
      ghpagesbranch:
        required: false
        default: gh-pages
        type: string
      ghpagesfolder:
        required: false
        default: /
        type: string
      templatedir:
        required: false
        default: ontdocscript/resources/html/
        type: string
      createcollections:
        required: false
        default: false
        type: boolean
      preferredlang:
        required: false
        default: en
        type: string
      license:
        required: false
        default: ""
        type: string
      logourl:
        required: false
        default: ""
        type: string
      metadatatable:
        required: false
        default: false
        type: boolean
      createnonNSPages:
        required: false
        default: false
        type: boolean
      createVOWL:
        required: false
        default: false
        type: boolean
      ogcapifeatures:
        required: false
        default: true
        type: boolean
      startconcept:
        required: false
        default: ""
        type: string

jobs:
  sample-action:
    name: Ontology Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Checkout tools repo
        uses: actions/checkout@v3
        with:
          repository: sparqlunicorn/sparqlunicornGoesGIS-ontdoc
          path: ontdocscript
      - name: Run sample action
        run: |
          sudo apt-get install wget python3-venv python3-wheel -y
          sudo pip3 install wheel pylode==2.13.2 rdflib shapely
          cp ontdocscript/docgeneration.py .
          cp ontdocscript/prefixes.json .
          python3 docgeneration.py "${{inputs.rdffilepath}}" "${{inputs.docpath}}" "${{inputs.prefixns}}" "${{inputs.prefixnsshort}}" "${{inputs.indexpages}}" "${{inputs.createcollections}}" "${{inputs.preferredlang}}" "${{inputs.license}}" "${{inputs.logourl}}" "${{inputs.metadatatable}}" "${{inputs.createnonNSPages}}" "${{inputs.createVOWL}}" "${{inputs.ogcapifeatures}}" "${{inputs.startconcept}}" "https://${{github.repository_owner}}.github.io/${{ github.event.repository.name }}" "${{inputs.templatedir}}" 
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v4
        if: ${{ inputs.ghpages }}
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: ${{inputs.ghpagesbranch}}
          FOLDER: ${{inputs.docpath}}/
          TARGET-FOLDER: ${{inputs.ghpagesfolder}}
      #- name: Create build-output artifact
      #  uses: actions/upload-artifact@master
      #  with:
      #   name: build-output
      #    path: docs/
