name: SPARQLing Unicorn Ontology Documentation

permissions:
  contents: write

env:
  theref: ${{github.ref}}

on:
  workflow_call:
    inputs:
      rdffilepath:
        required: true
        type: string
      docpath:
        required: true
        default: docs 
        type: string
      prefixns:
        required: true
        default: http://www.sparqlunicorn.link/data/
        type: string
      prefixnsshort:
        required: true
        default: suni
        type: string
      indexpages:
        required: false
        default: true
        type: boolean
      ghpages:
        required: false
        default: true
        type: boolean
      ghpagesbranch:
        required: false
        default: gh-pages
        type: string
      ghpagesfolder:
        required: false
        default: /
        type: string
      templatedir:
        required: false
        default: ontdocscript/resources/html/
        type: string
      createcollections:
        required: false
        default: false
        type: boolean
      preferredlang:
        required: false
        default: en
        type: string
      license:
        required: false
        default: ""
        type: string
      logourl:
        required: false
        default: ""
        type: string
      metadatatable:
        required: false
        default: false
        type: boolean
      createnonNSPages:
        required: false
        default: false
        type: boolean
      createVOWL:
        required: false
        default: false
        type: boolean
      ogcapifeatures:
        required: false
        default: true
        type: boolean
      iiif:
        required: false
        default: true
        type: boolean
      startconcept:
        required: false
        default: ""
        type: string
      offlinecompat:
        required: false
        default: false
        type: boolean
      exports:
        required: false
        default: "ttl"
        type: string
      datasettitle:
        required: false
        default: ""
        type: string

jobs:
  ontdoc-action:
    name: Ontology Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Checkout tools repo
        uses: actions/checkout@v3
        with:
          repository: sparqlunicorn/sparqlunicornGoesGIS-ontdoc
          ref: ${{theref}}
          path: ontdocscript
      - name: Run sample action
        run: |
          sudo pip3 install rdflib shapely pillow
          cp ontdocscript/docgeneration.py .
          cp ontdocscript/prefixes.json .
          python3 docgeneration.py --input "${{inputs.rdffilepath}}" --output "${{inputs.docpath}}" --prefixns "${{inputs.prefixns}}" --prefixnsshort "${{inputs.prefixnsshort}}" --createIndexPages "${{inputs.indexpages}}" --createCollections "${{inputs.createcollections}}" --labellang "${{inputs.preferredlang}}" --license "${{inputs.license}}" --logourl "${{inputs.logourl}}" --metadatatable "${{inputs.metadatatable}}" --nonnspages "${{inputs.createnonNSPages}}" --createvowl "${{inputs.createVOWL}}" --ogcapifeatures "${{inputs.ogcapifeatures}}" --iiif "${{inputs.iiif}}" --startconcept "${{inputs.startconcept}}" --deploypath "https://${{github.repository_owner}}.github.io/${{ github.event.repository.name }}" --templatepath "${{inputs.templatedir}}" --offlinecompat "${{inputs.offlinecompat}}" --exports "${{inputs.exports}}" --datasettitle "${{inputs.datasettitle}}" 
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v4
        if: ${{ inputs.ghpages }}
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: ${{inputs.ghpagesbranch}}
          FOLDER: ${{inputs.docpath}}/
          TARGET-FOLDER: ${{inputs.ghpagesfolder}}
