name: SPARQLing Unicorn Ontology Documentation

permissions:
  contents: write
 
on:
  workflow_call:
    inputs:
      version:
        required: false
        type: string
        default: main
      rdffilepath:
        required: false
        default: None
        type: string
      rdffilebranch:
        required: false
        default: ${{ github.event.repository.default_branch }}
        type: string
      docpath:
        required: false
        default: docs 
        type: string
      prefixns:
        required: false
        default: None
        type: string
      prefixnsshort:
        required: false
        default: suni
        type: string
      indexpages:
        required: false
        default: true
        type: boolean
      ghpages:
        required: false
        default: true
        type: boolean
      ghpagesbranch:
        required: false
        default: gh-pages
        type: string
      ghpagesfolder:
        required: false
        default: ""
        type: string
      checkout:
        required: false
        default: true
        type: boolean
      templatedir:
        required: false
        default: resources/html/
        type: string
      createcollections:
        required: false
        default: false
        type: boolean
      preferredlang:
        required: false
        default: en
        type: string
      license:
        required: false
        default: ""
        type: string
      logourl:
        required: false
        default: ""
        type: string
      metadatatable:
        required: false
        default: false
        type: boolean
      createnonNSPages:
        required: false
        default: false
        type: boolean
      createVOWL:
        required: false
        default: false
        type: boolean
      ogcapifeatures:
        required: false
        default: true
        type: boolean
      iiif:
        required: false
        default: true
        type: boolean
      solid:
        required: false
        default: false
        type: boolean
      ckan:
        required: false
        default: true
        type: boolean
      startconcept:
        required: false
        default: ""
        type: string
      offlinecompat:
        required: false
        default: false
        type: boolean
      exports:
        required: false
        default: "ttl"
        type: string
      sleepafter:
        required: false
        default: 0
        type: number
      sleepbefore:
        required: false
        default: 0
        type: number
      datasettitle:
        required: false
        default: ""
        type: string
      publisher:
        required: false
        default: ""
        type: string
      publishingorg:
        required: false
        default: ""
        type: string


jobs:
  ontdoc-action:
    name: Ontology Documentation
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - name: Checkout repo
        if: ${{ inputs.checkout }}
        uses: actions/checkout@v4
        with:
          ref: "${{inputs.rdffilebranch}}"
      - name: Checkout tools repo
        id: checkout_tools
        uses: actions/checkout@v4
        continue-on-error: true
        with:
          repository: sparqlunicorn/sparqlunicornGoesGIS-ontdoc
          ref: "${{inputs.version}}"
          path: ontdocscript
      - name: Checkout tools repo fallback
        if: steps.checkout_tools.outcome != 'success'
        uses: actions/checkout@v4
        with:
          repository: sparqlunicorn/sparqlunicornGoesGIS-ontdoc
          ref: "main"
          path: ontdocscript    
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install rdflib pillow shapely requests
      - name: Generate Ontology Documentation
        run: |
          ls
          pwd
          sleep "${{inputs.sleepbefore}}"
          python ontdocscript/src/sparqlunicorn_ontdoc/docgeneration.py --input "${{inputs.rdffilepath}}" --output "${{inputs.docpath}}" --prefixns "${{inputs.prefixns}}" --prefixnsshort "${{inputs.prefixnsshort}}" --createIndexPages "${{inputs.indexpages}}" --createCollections "${{inputs.createcollections}}" --labellang "${{inputs.preferredlang}}" --license "${{inputs.license}}" --logourl "${{inputs.logourl}}" --metadatatable "${{inputs.metadatatable}}" --nonnspages "${{inputs.createnonNSPages}}" --createvowl "${{inputs.createVOWL}}" --ogcapifeatures "${{inputs.ogcapifeatures}}" --iiif "${{inputs.iiif}}" --ckan "${{inputs.ckan}}" --startconcept "${{inputs.startconcept}}" --repository "${{ github.server_url }}/${{ github.repository }}" --deploypath "https://${{github.repository_owner}}.github.io/${{ github.event.repository.name }}/${{ inputs.ghpagesfolder }}" --templatepath "${{inputs.templatedir}}" --offlinecompat "${{inputs.offlinecompat}}" --publishingorg "${{inputs.publishingorg}}" --publisher "${{inputs.publisher}}" --exports "${{inputs.exports}}" --datasettitle "${{inputs.datasettitle}}"    
          sleep "${{inputs.sleepafter}}"
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v4
        if: ${{ inputs.ghpages }}
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: ${{inputs.ghpagesbranch}}
          FOLDER: ${{inputs.docpath}}/
          clean: false
          TARGET-FOLDER: ${{inputs.ghpagesfolder}}
